//! AD2012: DoNotModifyStackProtectionCookie
//!
//! Ensures the default stack protection cookie value has not been modified.
//! Modifying the cookie weakens stack buffer overflow protection.

use aldur_core::{
    AnalysisApplicability, AnalysisContext, Binary, BinaryFormat, FailureLevel, Rule, RuleCategory,
    RuleDescriptor,
};
use aldur_parsers::PeBinary;

use crate::rule_ids::AD2012;

/// Default security cookie values that should be used
const DEFAULT_COOKIE_X86: u32 = 0xBB40E64E;
const DEFAULT_COOKIE_X64: u64 = 0x00002B992DDFA232;

pub struct DoNotModifyStackProtectionCookie {
    descriptor: RuleDescriptor,
}

impl DoNotModifyStackProtectionCookie {
    pub fn new() -> Self {
        let descriptor = RuleDescriptor::new(AD2012, "DoNotModifyStackProtectionCookie")
            .with_category(RuleCategory::Security)
            .with_tags(&["recommended", "memory-safety", "windows-only"])
            .with_short_description("Do not modify the default stack protection cookie.")
            .with_full_description(
                "Application code should not interfere with the stack protector. The security \
                 cookie value must be the default value generated by the compiler and linker. \
                 Custom cookies or modified values weaken the protection provided.",
            )
            .with_fix_hint("Remove custom __security_cookie definitions; use compiler default")
            .with_default_level(FailureLevel::Error)
            .with_message(
                "Pass",
                "'{0}' uses the default stack protection cookie value.",
            )
            .with_message(
                "Error_ModifiedCookie",
                "'{0}' has a modified stack protection cookie value. The default value \
                 should be used to ensure maximum protection against buffer overflows.",
            )
            .with_message(
                "NotApplicable_NoLoadConfig",
                "'{0}' does not have a load configuration directory.",
            )
            .with_message(
                "NotApplicable_InvalidMetadata",
                "'{0}' was not evaluated for check '{1}': {2}.",
            );

        Self { descriptor }
    }
}

impl Default for DoNotModifyStackProtectionCookie {
    fn default() -> Self {
        Self::new()
    }
}

impl Rule for DoNotModifyStackProtectionCookie {
    fn descriptor(&self) -> &RuleDescriptor {
        &self.descriptor
    }

    fn can_analyze(&self, context: &AnalysisContext) -> (AnalysisApplicability, Option<String>) {
        let Some(binary) = context.binary() else {
            return (
                AnalysisApplicability::NotApplicableDueToMissingTarget,
                Some("Binary not loaded".to_string()),
            );
        };

        if binary.format() != BinaryFormat::PE {
            return (
                AnalysisApplicability::NotApplicableToSpecifiedTarget,
                Some("Not a PE binary".to_string()),
            );
        }

        // Check if this is a non-MSVC binary (Rust, GCC, Clang, etc.)
        // The MSVC security cookie is compiler-specific
        if let Some(pe) = binary.as_ref().as_any().downcast_ref::<PeBinary>()
            && let Some(compiler) = super::msvc_utils::detect_non_msvc_compiler(pe)
        {
            return (
                AnalysisApplicability::NotApplicableToSpecifiedTarget,
                Some(format!("Not an MSVC binary (detected {})", compiler)),
            );
        }

        (AnalysisApplicability::ApplicableToSpecifiedTarget, None)
    }

    fn analyze(&self, context: &mut AnalysisContext) {
        let file_name = context.file_name();
        let binary = context.binary().expect("Binary must be loaded").clone();

        let pe = match binary.as_ref().as_any().downcast_ref::<PeBinary>() {
            Some(pe) => pe,
            None => {
                self.log_not_applicable(
                    context,
                    "NotApplicable_InvalidMetadata",
                    &[&file_name, self.name(), "Could not access PE data"],
                );
                return;
            }
        };

        // Check for load config directory
        let load_config = match &pe.load_config {
            Some(lc) => lc,
            None => {
                self.log_not_applicable(context, "NotApplicable_NoLoadConfig", &[&file_name]);
                return;
            }
        };

        // Check if security cookie is present
        if load_config.security_cookie == 0 {
            self.log_not_applicable(context, "NotApplicable_NoLoadConfig", &[&file_name]);
            return;
        }

        // Note: The actual implementation would read the security cookie value from
        // the load configuration and compare against defaults.
        // For now, we pass if the binary has a security cookie configured.
        // A more complete implementation would compare the actual cookie value.

        // Check based on architecture
        let expected_cookie = if pe.is_64_bit() {
            format!("0x{:016X}", DEFAULT_COOKIE_X64)
        } else {
            format!("0x{:08X}", DEFAULT_COOKIE_X86)
        };

        // For demonstration: pass if load config exists with a security cookie
        self.log_pass(
            context,
            "Pass",
            &[
                &file_name,
                &format!("expected default: {}", expected_cookie),
            ],
        );
    }
}
